"""Generate `azalea-client/src/plugins/interact/predict/data.rs`.

Inputs:
  right_click.json  output of RightClickDump.java (blocks, items, lookup tables)
  entities.tsv      entity id, class, declarer of interact, declarer of mobInteract
                    (from entities.py over the decompiled 26.1.2 sources)
  client.jar        for the campfire_cooking recipes (campfire inputs)
  builtin.rs        azalea-registry/src/builtin.rs, to map ids to variant names

Usage: python3 gen.py right_click.json entities.tsv client.jar builtin.rs > data.rs
"""
import json
import re
import sys
import zipfile

data = json.load(open(sys.argv[1]))
entity_rows = [line.rstrip("\n").split("\t") for line in open(sys.argv[2]) if line.strip()]
jar = zipfile.ZipFile(sys.argv[3])
builtin = open(sys.argv[4]).read()


def variants(enum):
    start = builtin.index(f"enum {enum} {{")
    end = builtin.index("\n}", start)
    return {m.group(2): m.group(1) for m in re.finditer(r"(\w+) => \"([\w.]+)\"", builtin[start:end])}


BLOCK = variants("BlockKind")
ITEM = variants("ItemKind")
ENTITY = variants("EntityKind")


def names(table, ids):
    out = []
    for i in sorted(set(ids)):
        if i not in table:
            sys.exit(f"unknown registry id {i}")
        out.append(table[i])
    return out


def emit_matches(fn, kind, table, ids):
    items = names(table, ids)
    print(f"pub fn {fn}(kind: {kind}) -> bool {{")
    print(f"    use {kind}::*;")
    print("    matches!(")
    print("        kind,")
    print("        " + "\n            | ".join(items))
    print("    )")
    print("}")
    print()


def emit_classes(fn, enum, kind, table, by_id, doc):
    classes = sorted({c for c in by_id.values() if c not in ("-",)} - {"Default"})
    print(f"/// {doc}")
    print("#[derive(Clone, Copy, Debug, Eq, PartialEq)]")
    print(f"pub enum {enum} {{")
    print("    /// The base-class default.")
    print("    Default,")
    for c in classes:
        print(f"    {c},")
    print("}")
    print()
    print(f"pub fn {fn}(kind: {kind}) -> {enum} {{")
    print(f"    use {kind}::*;")
    print("    match kind {")
    for c in classes:
        ids = [i for i, v in by_id.items() if v == c]
        print("        " + "\n        | ".join(names(table, ids)) + f" => {enum}::{c},")
    print(f"        _ => {enum}::Default,")
    print("    }")
    print("}")
    print()


def default_if(base):
    return lambda c: "Default" if c in base else c


print("//! Generated by `codegen/right_click/gen.py` from the vanilla 26.1.2 client")
print("//! (`RightClickDump.java`, the decompiled entity sources and the jar's")
print("//! recipes). Do not edit by hand; regenerate when updating the version.")
print()
print("use azalea_registry::builtin::{BlockKind, EntityKind, ItemKind};")
print()

block_base = default_if({"BlockBehaviour", "-"})
emit_classes("block_use_item_on", "BlockUseItemOn", "BlockKind", BLOCK,
             {b: block_base(v[0]) for b, v in data["blocks"].items()},
             "The class that declares `useItemOn` for a block.")
emit_classes("block_use_without_item", "BlockUseWithoutItem", "BlockKind", BLOCK,
             {b: block_base(v[1]) for b, v in data["blocks"].items()},
             "The class that declares `useWithoutItem` for a block.")

item_base = default_if({"Item", "-"})
emit_classes("item_use", "ItemUse", "ItemKind", ITEM,
             {i: item_base(v["use"]) for i, v in data["items"].items()},
             "The class that declares `use` for an item.")
emit_classes("item_use_on", "ItemUseOn", "ItemKind", ITEM,
             {i: item_base(v["use_on"]) for i, v in data["items"].items()},
             "The class that declares `useOn` for an item.")
emit_classes("item_interact_living_entity", "ItemInteractLivingEntity", "ItemKind", ITEM,
             {i: item_base(v["interact_living"]) for i, v in data["items"].items()},
             "The class that declares `interactLivingEntity` for an item.")

print("/// The block a `BlockItem` places, or `None` for other items.")
print("pub fn item_places(kind: ItemKind) -> Option<BlockKind> {")
print("    Some(match kind {")
for i, v in sorted(data["items"].items()):
    if v["places"]:
        print(f"        ItemKind::{ITEM[i]} => BlockKind::{BLOCK[v['places']]},")
print("        _ => return None,")
print("    })")
print("}")
print()

emit_matches("is_hanging_sign_item", "ItemKind", ITEM, [i for i, v in data["items"].items() if v["hanging_sign"]])
emit_matches("is_spawn_egg", "ItemKind", ITEM, [i for i, v in data["items"].items() if v["spawn_egg"]])

print("/// `AxeItem.STRIPPABLES` keys.")
emit_matches("is_strippable", "BlockKind", BLOCK, data["strippable"])
print("/// `ShovelItem.FLATTENABLES` keys.")
emit_matches("is_flattenable", "BlockKind", BLOCK, data["flattenable"])
print("/// `HoneycombItem.WAXABLES` keys.")
emit_matches("is_waxable", "BlockKind", BLOCK, data["waxable"])
print("/// `HoneycombItem.WAX_OFF_BY_BLOCK` keys.")
emit_matches("is_waxed", "BlockKind", BLOCK, data["wax_off"])
print("/// `WeatheringCopper.PREVIOUS_BY_BLOCK` keys (blocks an axe can scrape).")
emit_matches("is_scrapable", "BlockKind", BLOCK, data["scrapable"])
print("/// `FlowerPotBlock.POTTED_BY_CONTENT` keys (blocks that can go in a pot).")
emit_matches("is_pottable", "BlockKind", BLOCK, data["pottable"])
print("/// `ComposterBlock.COMPOSTABLES` keys.")
emit_matches("is_compostable", "ItemKind", ITEM, data["compostable"])
print("/// Blocks whose default state `canBeReplaced()`.")
emit_matches("is_replaceable", "BlockKind", BLOCK, data["replaceable"])
print("/// Doors and trapdoors whose `BlockSetType.canOpenByHand()`.")
emit_matches("opens_by_hand", "BlockKind", BLOCK, data["opens_by_hand"])

# campfire inputs: ingredients of every campfire_cooking recipe.
campfire = set()
for name in jar.namelist():
    if name.startswith("data/minecraft/recipe/") and name.endswith(".json"):
        recipe = json.loads(jar.read(name))
        if recipe.get("type") != "minecraft:campfire_cooking":
            continue
        ingredient = recipe["ingredient"]
        for entry in ingredient if isinstance(ingredient, list) else [ingredient]:
            if entry.startswith("#"):
                sys.exit(f"tag ingredient {entry} in {name} is not handled")
            campfire.add(entry.removeprefix("minecraft:"))
print("/// Ingredients of the `campfire_cooking` recipes (`RecipePropertySet.CAMPFIRE_INPUT`).")
emit_matches("is_campfire_input", "ItemKind", ITEM, campfire)

entity_base = default_if({"Entity", "Mob", "-"})
emit_classes("entity_interact", "EntityInteract", "EntityKind", ENTITY,
             {row[0]: entity_base(row[2]) for row in entity_rows},
             "The class that overrides `interact` for an entity (`Entity` and `Mob` are the defaults).")
emit_classes("entity_mob_interact", "EntityMobInteract", "EntityKind", ENTITY,
             {row[0]: entity_base(row[3]) for row in entity_rows},
             "The class that overrides `mobInteract` for an entity.")
print("/// Entities that are a `Mob` (and so go through `Mob.interact`).")
mob_classes = {row[0] for row in entity_rows if row[4] == "True"}
emit_matches("is_mob", "EntityKind", ENTITY, mob_classes)
